channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=24.3.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.0
  - lightgbm==4.5.0
  - matplotlib==3.9.2
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==6.1.0
  - pyarrow==18.0.0
  - scikit-learn==1.5.2
  - scipy==1.13.1
name: mlflow-env
